/*
 * WeatherAPI2.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WeatherAPI2.Standard;
using WeatherAPI2.Standard.Utilities;


namespace WeatherAPI2.Standard.Models
{
    public class Coord : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double lon;
        private double lat;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lon")]
        public double Lon 
        { 
            get 
            {
                return this.lon; 
            } 
            set 
            {
                this.lon = value;
                onPropertyChanged("Lon");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lat")]
        public double Lat 
        { 
            get 
            {
                return this.lat; 
            } 
            set 
            {
                this.lat = value;
                onPropertyChanged("Lat");
            }
        }
    }
} 