/*
 * WeatherAPI2.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WeatherAPI2.Standard;
using WeatherAPI2.Standard.Utilities;


namespace WeatherAPI2.Standard.Models
{
    public class MyJSONWeatherObject : BaseModel 
    {
        // These fields hold the values for the public properties.
        private object myWeather;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("My Weather")]
        public object MyWeather 
        { 
            get 
            {
                return this.myWeather; 
            } 
            set 
            {
                this.myWeather = value;
                onPropertyChanged("MyWeather");
            }
        }
    }
} 