/*
 * WeatherAPI2.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WeatherAPI2.Standard;
using WeatherAPI2.Standard.Utilities;


namespace WeatherAPI2.Standard.Models
{
    public class Weather : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Coord coord;
        private List<Models.Weather1> weather;
        private string mbase;
        private Models.Main main;
        private int visibility;
        private Models.Wind wind;
        private Models.Clouds clouds;
        private int dt;
        private Models.Sys sys;
        private int timezone;
        private int id;
        private string name;
        private int cod;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("coord")]
        public Models.Coord Coord 
        { 
            get 
            {
                return this.coord; 
            } 
            set 
            {
                this.coord = value;
                onPropertyChanged("Coord");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("weather")]
        public List<Models.Weather1> WeatherProp 
        { 
            get 
            {
                return this.weather; 
            } 
            set 
            {
                this.weather = value;
                onPropertyChanged("WeatherProp");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("base")]
        public string Base 
        { 
            get 
            {
                return this.mbase; 
            } 
            set 
            {
                this.mbase = value;
                onPropertyChanged("Base");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("main")]
        public Models.Main Main 
        { 
            get 
            {
                return this.main; 
            } 
            set 
            {
                this.main = value;
                onPropertyChanged("Main");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("visibility")]
        public int Visibility 
        { 
            get 
            {
                return this.visibility; 
            } 
            set 
            {
                this.visibility = value;
                onPropertyChanged("Visibility");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("wind")]
        public Models.Wind Wind 
        { 
            get 
            {
                return this.wind; 
            } 
            set 
            {
                this.wind = value;
                onPropertyChanged("Wind");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clouds")]
        public Models.Clouds Clouds 
        { 
            get 
            {
                return this.clouds; 
            } 
            set 
            {
                this.clouds = value;
                onPropertyChanged("Clouds");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("dt")]
        public int Dt 
        { 
            get 
            {
                return this.dt; 
            } 
            set 
            {
                this.dt = value;
                onPropertyChanged("Dt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sys")]
        public Models.Sys Sys 
        { 
            get 
            {
                return this.sys; 
            } 
            set 
            {
                this.sys = value;
                onPropertyChanged("Sys");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("timezone")]
        public int Timezone 
        { 
            get 
            {
                return this.timezone; 
            } 
            set 
            {
                this.timezone = value;
                onPropertyChanged("Timezone");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cod")]
        public int Cod 
        { 
            get 
            {
                return this.cod; 
            } 
            set 
            {
                this.cod = value;
                onPropertyChanged("Cod");
            }
        }
    }
} 