/*
 * WeatherAPI2.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using WeatherAPI2.Standard.Controllers;
using WeatherAPI2.Standard.Http.Client;
using WeatherAPI2.Standard.Utilities;

namespace WeatherAPI2.Standard
{
    public partial class WeatherAPI2Client
    {

        /// <summary>
        /// Singleton access to SimpleGetWeather controller
        /// </summary>
        public SimpleGetWeatherController SimpleGetWeather
        {
            get
            {
                return SimpleGetWeatherController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to DynamicGetWeatherThatTakesLocationAndAPIKey controller
        /// </summary>
        public DynamicGetWeatherThatTakesLocationAndAPIKeyController DynamicGetWeatherThatTakesLocationAndAPIKey
        {
            get
            {
                return DynamicGetWeatherThatTakesLocationAndAPIKeyController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public WeatherAPI2Client() { }
        #endregion
    }
}