/*
 * WeatherAPI2.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using WeatherAPI2.Standard;
using WeatherAPI2.Standard.Utilities;
using WeatherAPI2.Standard.Http.Request;
using WeatherAPI2.Standard.Http.Response;
using WeatherAPI2.Standard.Http.Client;
using WeatherAPI2.Standard.Exceptions;

namespace WeatherAPI2.Standard.Controllers
{
    public partial class DynamicGetWeatherThatTakesLocationAndAPIKeyController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static DynamicGetWeatherThatTakesLocationAndAPIKeyController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static DynamicGetWeatherThatTakesLocationAndAPIKeyController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new DynamicGetWeatherThatTakesLocationAndAPIKeyController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="q">Required parameter: City Name</param>
        /// <param name="appid">Required parameter: API Key</param>
        /// <return>Returns the Models.Weather response from the API call</return>
        public Models.Weather GetWeatherEndpointDynamic(string q, string appid)
        {
            Task<Models.Weather> t = GetWeatherEndpointDynamicAsync(q, appid);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="q">Required parameter: City Name</param>
        /// <param name="appid">Required parameter: API Key</param>
        /// <return>Returns the Models.Weather response from the API call</return>
        public async Task<Models.Weather> GetWeatherEndpointDynamicAsync(string q, string appid)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/weather");

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "q", q },
                { "appid", appid }
            },ArrayDeserializationFormat,ParameterSeparator);


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.Weather>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

    }
} 